version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: minikarych/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: minikarych/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs:/usr/share/nginx/html/api/docs/
      - ../frontend/build:/usr/share/nginx/html/
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value: